# Generated by Django 4.2 on 2023-05-02 02:57

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GameInstruction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, unique=True)),
                ("content", django_quill.fields.QuillField()),
            ],
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                ("game_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("LOBBY", "LOBBY"),
                            ("IN-GAME", "IN-GAME"),
                            ("COMPLETED", "COMPLETED"),
                            ("ARCHIVE", "ARCHIVE"),
                            ("ARCHIVED", "ARCHIVED"),
                        ],
                        default="LOBBY",
                        max_length=10,
                    ),
                ),
                (
                    "p1_status",
                    models.CharField(
                        choices=[
                            ("UNREADY", "UNREADY"),
                            ("READY", "READY"),
                            ("IN-GAME", "IN-GAME"),
                            ("LEFT", "LEFT"),
                            ("REMATCH", "REMATCH"),
                        ],
                        default="UNREADY",
                        max_length=10,
                    ),
                ),
                (
                    "p2_status",
                    models.CharField(
                        choices=[
                            ("UNREADY", "UNREADY"),
                            ("READY", "READY"),
                            ("IN-GAME", "IN-GAME"),
                            ("LEFT", "LEFT"),
                            ("REMATCH", "REMATCH"),
                        ],
                        default="UNREADY",
                        max_length=10,
                    ),
                ),
                ("round", models.IntegerField(default=1)),
                (
                    "plays",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(blank=True), default=list, size=9
                    ),
                ),
                (
                    "spaces",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(blank=True), default=list, size=9
                    ),
                ),
                ("winner", models.IntegerField(blank=True, default=0)),
                ("loser", models.IntegerField(blank=True, default=0)),
                (
                    "privacy",
                    models.CharField(
                        choices=[("Public", "Public"), ("Private", "Private")],
                        default="Public",
                        max_length=7,
                    ),
                ),
                ("password", models.CharField(default="", max_length=15)),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("ended", models.DateTimeField(blank=True, null=True)),
                (
                    "player_one",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_one_games",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "player_two",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_two_games",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
