# Generated by Django 4.2.1 on 2023-05-23 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("magic_fifteen", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="player_one",
        ),
        migrations.RemoveField(
            model_name="game",
            name="player_two",
        ),
        migrations.AddField(
            model_name="game",
            name="player_one_content_type",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="player_one_games",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="player_one_object_id",
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="player_two_content_type",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="player_two_games",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="player_two_object_id",
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
