# Generated by Django 4.2.1 on 2023-06-02 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "magic_fifteen",
            "0002_remove_game_player_one_remove_game_player_two_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="GameInstruction",
        ),
        migrations.AlterField(
            model_name="game",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="p1_status",
            field=models.CharField(
                choices=[
                    ("UNREADY", "UNREADY"),
                    ("READY", "READY"),
                    ("IN-GAME", "IN-GAME"),
                    ("LEFT", "LEFT"),
                    ("ABANDONED", "ABANDONED"),
                    ("REMATCH", "REMATCH"),
                ],
                default="UNREADY",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="p2_status",
            field=models.CharField(
                choices=[
                    ("UNREADY", "UNREADY"),
                    ("READY", "READY"),
                    ("IN-GAME", "IN-GAME"),
                    ("LEFT", "LEFT"),
                    ("ABANDONED", "ABANDONED"),
                    ("REMATCH", "REMATCH"),
                ],
                default="UNREADY",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="password",
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="status",
            field=models.CharField(
                choices=[
                    ("LOBBY", "LOBBY"),
                    ("REMATCH", "REMATCH"),
                    ("IN-GAME", "IN-GAME"),
                    ("COMPLETED", "COMPLETED"),
                    ("ARCHIVE", "ARCHIVE"),
                    ("ARCHIVED", "ARCHIVED"),
                ],
                default="LOBBY",
                max_length=10,
            ),
        ),
    ]
