# Generated by Django 5.0.4 on 2024-11-06 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("magic_fifteen", "0003_delete_gameinstruction_alter_game_created_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="player_one_content_type",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="magic_fifteen_player_one_games",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="player_two_content_type",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="magic_fifteen_player_two_games",
                to="contenttypes.contenttype",
            ),
        ),
    ]
