# Generated by Django 4.2 on 2023-05-09 00:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("user_profiles", "0002_userprofile_email_verified_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="verification_code_expires_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="verification_code",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
