# Generated by Django 4.2.1 on 2023-06-22 01:39

from django.db import migrations, models
import user_profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profiles", "0004_userprofile_first_name_userprofile_last_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="banner",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=user_profiles.models.user_directory_path,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=user_profiles.models.user_directory_path,
            ),
        ),
    ]
